CREATE TABLE IF NOT EXISTS games(
  id serial PRIMARY KEY,
  name VARCHAR(64) UNIQUE NOT NULL,
  player_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
