CREATE TABLE IF NOT EXISTS games(
  id serial PRIMARY KEY,
  name VARCHAR(64) UNIQUE NOT NULL,
  phase VARCHAR(64) NOT NULL DEFAULT 'Day',
  round INT NOT NULL DEFAULT 1,
  player_ids INT[] DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
