DROP TYPE alignment CASCADE;
DROP TYPE rarity CASCADE;

DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS ability_details CASCADE;
DROP TABLE IF EXISTS passive_details CASCADE;
DROP TABLE IF EXISTS role_abilities_join CASCADE;
DROP TABLE IF EXISTS role_passives_join CASCADE;
DROP TABLE IF EXISTS status_details CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
