// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ability struct {
	ID                int32       `json:"id"`
	AbilityDetailsID  pgtype.Int4 `json:"ability_details_id"`
	PlayerInventoryID pgtype.Int4 `json:"player_inventory_id"`
}

type AbilityDetail struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	RoleID      pgtype.Int4 `json:"role_id"`
	CategoryIds []int32     `json:"category_ids"`
	AnyAbility  pgtype.Bool `json:"any_ability"`
}

type Category struct {
	ID       int32       `json:"id"`
	Name     pgtype.Text `json:"name"`
	Priority pgtype.Int4 `json:"priority"`
}

type Game struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Phase     string           `json:"phase"`
	Round     int32            `json:"round"`
	PlayerIds []int32          `json:"player_ids"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type PassiveDetail struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type PlayerInventory struct {
	PlayerID        int32       `json:"player_id"`
	AbilityName     string      `json:"ability_name"`
	AbilityQuantity pgtype.Int4 `json:"ability_quantity"`
}

type Role struct {
	ID         int32       `json:"id"`
	Name       string      `json:"name"`
	Alignment  interface{} `json:"alignment"`
	AbilityIds []int32     `json:"ability_ids"`
	PassiveIds []int32     `json:"passive_ids"`
}

type StatusDetail struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}
