// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: passive_details.sql

package models

import (
	"context"
)

const createPassiveDetail = `-- name: CreatePassiveDetail :one
INSERT INTO passive_details (
  name, description 
) VALUES (
  $1, $2
)
RETURNING id, name, description
`

type CreatePassiveDetailParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreatePassiveDetail(ctx context.Context, arg CreatePassiveDetailParams) (PassiveDetail, error) {
	row := q.db.QueryRow(ctx, createPassiveDetail, arg.Name, arg.Description)
	var i PassiveDetail
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getPassiveDetail = `-- name: GetPassiveDetail :one
select id, name, description
from passive_details
where id = $1
`

func (q *Queries) GetPassiveDetail(ctx context.Context, id int32) (PassiveDetail, error) {
	row := q.db.QueryRow(ctx, getPassiveDetail, id)
	var i PassiveDetail
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
