// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: role_passive_join.sql

package models

import (
	"context"
)

const getAssociatedRolePassives = `-- name: GetAssociatedRolePassives :many
SELECT pd.id, pd.name, pd.description
FROM role_passives_join rpj
JOIN passive_details pd ON rpj.passive_id = pd.id
WHERE rpj.role_id = $1
`

func (q *Queries) GetAssociatedRolePassives(ctx context.Context, roleID int32) ([]PassiveDetail, error) {
	rows, err := q.db.Query(ctx, getAssociatedRolePassives, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PassiveDetail
	for rows.Next() {
		var i PassiveDetail
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
